### ISSUE TITLE
Mark calculation

### ISSUE THREAD

**Issue by ryanmartinneutrino** [qlicker/qlicker#191]
If a question is attempted multiple times, what mark is saved? For example, if they only answer the first of multiple attempts of a question and answer it correctly, are they penalized? I think that it makes sense for them not to be penalized (in participation or mark for that question).

**Comment by turnergarrow** [comment]
In terms of participation, answering the question any time it is asked will get you a participation mark for that question. For marks, each time it is asked counts as a new question. So if they only answer it the first time it is asked, then they will only get marks for that answer and the other attempts will count as 0. I can change this so that it takes the highest mark from all the attempts on a question and uses that as the mark for the question.
