### ISSUE TITLE
AWS S3 mandatory ?

### ISSUE THREAD

**Issue by Badatos** [qlicker/qlicker#336]
Hello,
It seems that your project needs a Amazon S3 account to work. is it true ? if not, How can we disable the AWS call ?
Maybe you can add a message about that on your readme.md ?

**Comment by ryanmartinneutrino** [comment]
Hi,
At this point, without modifying any code, you do need to set up an S3 account, which you can do for free for a year. This is to handle the upload of image files for questions and profile pictures. 

The file uploads are handled through the Slingshot meteor package, which can use other backends than S3.  Currently we've hardcoded it to use S3, which I agree is not ideal, but, it can take other backends. 
There are some instructions on Slingshot here (including how to set up S3):
https://github.com/CulturalMe/meteor-slingshot

The main reason to store on S3 is to offload the server running Qlicker from serving image files to a large number of users (we are using Qlicker in a class with 200 students, and planning to deploy to a much larger audience). 

I would definitely be open to adding more flexibility so that it's not hardcoded for S3. In fact, the first solution we used was based on storing the images in a database on the qlicker server, but we became considered about the load on the database. We chose Slingshot because the file uploads are done in the client's browser, so we can avoid sending image files to the app server altogether. 

Best,
RM

**Comment by Badatos** [comment]
thank you for you answer.
Do you think it will be possible to have a "light" version of qlicker where the image file upload will be disabled ? Maybe by just letting users insert image with an external URL.

**Comment by ReckoningReckoner** [comment]
Hi @Badatos, I have created #356 which will allow you to run Qlicker without file uploads. If it is not merged, you can always try using an s3 storage simulator.

**Comment by Badatos** [comment]
Hi @ReckoningReckoner,
Thank you for this PR ! I can now test this app easily, without having an AWS account or installing a simulator.

Maybe you can just precise in the Readme that when you haven't an AWS account you just have to run "meteor" (without the "--settings settings.json" option)
Thanks,

**Comment by ReckoningReckoner** [comment]
Reopening because it hasn’t fully been merged yet

**Comment by Badatos** [comment]
Hello !
It seems this issue still hasn't been merged. Can anybody can merge it please ?

**Comment by Viraj3f** [comment]
Should be safe to merge since it will not break any existing workflows. However, once #363 is fixed and settings.json is deprecated, this solution may not fully work anymore. Nonetheless, I don't see the harm in merging now.
