### ISSUE TITLE
GPL License

### ISSUE THREAD

**Issue by Viraj3f** [qlicker/qlicker#379]
Just noticed that this project is GPL licensed. Is this necessarily what we want? It's a highly restrictive license and I'm not if a private institutions would ever the use of this software if this is the case. Would an MIT/BSD be better?

**Comment by ryanmartinneutrino** [comment]
Yes, that is intentional, as GPL requires that any derivative software also be open sourced and licensed as GPL, if that software is distributed. That is, I think a private institution can fork and re-brand the software for their own institutional use without needing to release it; however, if they choose to sell or distribute it, then they have to open it up, as far as I understand...
