### ISSUE TITLE
All subpages within a course should have a prominent 'course home' button

### ISSUE THREAD

**Issue by PfeifferH** [qlicker/qlicker#394]

**Comment by ryanmartinneutrino** [comment]
Yes, actually, this brings up an issue that I've been thinking about. Currently, when you are on the site, you are never "in a course", so it does not make sense to have a course home button. However, I think it would make sense to have a state variable in page_container that indicates which course the user is currently "in", so that all the links (grades, homepage, question library) automatically refer specifically to a single course. There could be a dropdown in the top menu bar to change the course. This has several implications, especially with respect to the question library, that we should think carefully about.
