### ISSUE TITLE
Updating 'Support email' not working in docker image

### ISSUE THREAD

**Issue by zjevik** [qlicker/qlicker#510]
Hi,

I'm running the latest image (v1.3.9) from https://hub.docker.com/r/qlicker/qlicker/ .

Updating Support email through the admin interface doesn't change the value in the database. This was also present in 1.3.7 and 1.3.8 in the docker image.

I tried to find the log from Node.js but I couldn't locate it. It would maybe be beneficial if the docker image stored log file..

**Comment by ryanmartinneutrino** [comment]
Ok - it's updated on docker. Note that the app has to be restarted when the contact email is changed.

**Comment by zjevik** [comment]
Awesome, thanks Ryan! I didn't know that you can see the logs in Docker - I will check it out.

I'm at the Florida International University (math dept) and we currently use Learning Catalytics (Pierson) or iClickers in our classes.
I see no reason why not to use Qlicker instead. I would like to try it in one of my classes in Spring semester and, if successful, introduce it to my colleagues. I've requested Shibboleth authentication from our IT and I will let you know if I have any issues setting it up if our IT gets back to me. 

Unfortunately, they have the request for more than a month and it's not getting anywhere. I wish I could get the same attention from our IT as the for profit companies that implement other software for our students...

**Comment by ryanmartinneutrino** [comment]
yeah, we were using Learning Catalytics in my physics class before I took it over... I've also surveyed students and they seem to vastly prefer Qlicker over LC or iClicker...

If you want to set up a production version of qlicker, I can give you a few tips to do it easily with docker-compose. I have it running on an i7 8GB RAM currently, and it can probably do about 800 concurrent students. We're in the process of getting ITS to review the security so that we can use it for the whole university through the Shibboleth single sign on. Currently, we have about 4 courses that are using it (physics, health sciences).

**Comment by zjevik** [comment]
I really appreciate the docker image – setting it up with the instructions on GitHub didn’t take much time. I have it running on my own server where I plan on testing it before introducing it to the rest of the department. If you’re ok with it, I would contact you about the docker-compose in the future if we decide to use Qlicker for multiple courses.

We’re in the process of implementing IMathAS so this will have to wait.

Thank you for putting hard work into this project and having it on GitHub!

Best,
Ondrej
http://faculty.fiu.edu/~ozjevik/
